openedx/openedx-app-android

- dashboard/src/main/java/com/raccoongang/dashboard/presentation/DashboardViewModel.kt
Fixed the issue where Jetpack Compose was not refreshing the UI
> Fix dashboard pagination

- course/src/main/java/org/openedx/course/presentation/handouts/HandoutsViewModel.kt
- course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerViewModel.kt
- course/src/main/java/org/openedx/course/presentation/unit/video/VideoUnitViewModel.kt
- course/src/main/java/org/openedx/course/presentation/unit/video/VideoViewModel.kt
- dashboard/src/main/java/org/openedx/dashboard/presentation/DashboardViewModel.kt
- discussion/src/test/java/org/openedx/discussion/presentation/comments/DiscussionCommentsViewModelTest.kt
- profile/src/main/java/org/openedx/profile/presentation/profile/ProfileViewModel.kt
Remove unused e.printStackTrace()
Fix tests logs
> Fix testProdReleaseUnitTest task

- course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt
Added CourseSectionCard icon change depending on completion status
> CourseSectionCard icon fix

- .github/workflows/unit_tests.yml
- app/build.gradle
- app/src/main/AndroidManifest.xml
- auth/build.gradle
- auth/src/main/AndroidManifest.xml
- build.gradle
- core/build.gradle
- course/build.gradle
- course/src/main/AndroidManifest.xml
- dashboard/build.gradle
- dashboard/src/androidTest/java/org/openedx/dashboard/presentation/MyCoursesScreenTest.kt
- discovery/build.gradle
- discovery/src/androidTest/java/org/openedx/discovery/presentation/DiscoveryScreenTest.kt
- discussion/build.gradle
- discussion/src/main/AndroidManifest.xml
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- profile/build.gradle
- profile/src/main/AndroidManifest.xml
Upgraded targetSdk, kotlin, compose, java, fragment, room and gradle versions
> Dependency versions upgrade

- app/build.gradle
- app/proguard-rules.pro
- build.gradle
- core/consumer-rules.pro
- core/proguard-rules.pro
- settings.gradle
Fixed Gradle 8 and Java 17 issues
https://issuetracker.google.com/issues/227160052
> Fixed release build with proguard

- course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt
- course/src/main/java/org/openedx/course/presentation/unit/video/VideoUnitFragment.kt
- course/src/main/java/org/openedx/course/presentation/unit/video/YoutubeVideoUnitFragment.kt
A user can jump to the desired moment of the video by clicking on the transcription
- Native player
https://github.com/openedx/openedx-app-android/assets/141041606/0ed41272-c00e-4eb2-a5e1-9dcea2e09638
- Youtube player
https://github.com/openedx/openedx-app-android/assets/141041606/19f6c68d-280a-471c-8d60-027966d85d63
> Transcription navigation

- .github/ISSUE_TEMPLATE/roadmap-entry.md
Testing out a new basic roadmap entry template for new issues created in this repository.
> [docs] adding new github project issue template

- course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt
- course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerFragment.kt
- course/src/main/res/layout-land/fragment_course_unit_container.xml
- course/src/main/res/layout-w600dp-h480dp/fragment_course_unit_container.xml
- course/src/main/res/layout/fragment_course_unit_container.xml
Fixed: Back button padding on CourseUnitContainerFragment on screen rotation.
> Fixed: Back button padding

- core/build.gradle
Small refactoring to prevent code duplication
> refactor: build config fields

- app/src/main/java/org/openedx/app/AppRouter.kt
- core/src/main/java/org/openedx/core/data/model/CourseDates.kt
- core/src/main/java/org/openedx/core/domain/model/CourseDateBlock.kt
- core/src/main/java/org/openedx/core/domain/model/CourseStructure.kt
- course/src/main/java/org/openedx/course/presentation/CourseRouter.kt
- course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
- course/src/main/java/org/openedx/course/presentation/dates/CourseDatesViewModel.kt
- course/src/main/java/org/openedx/course/presentation/section/CourseSectionFragment.kt
- course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerFragment.kt
- Update CourseDateBlock Model
- Add Underline text decorations for clickable text
- Navigate to Component Screen by tapping hyperlinks
- Maintain stack of navigation
> feat: Add hyperlink for assessments in Dates Tab

- app/src/main/java/org/openedx/app/AnalyticsManager.kt
- app/src/main/java/org/openedx/app/di/AppModule.kt
Analytics manager config new realisation
> fix: new config in AnalyticsManager

- course/src/main/java/org/openedx/course/presentation/unit/video/VideoUnitViewModel.kt
I fixed the NetworkOnMainThreadException when trying to get a video transcription.
> fix: crash when trying to get video transcription in main thread

- app/src/main/java/org/openedx/app/di/AppModule.kt
- app/src/main/java/org/openedx/app/di/ScreenModule.kt
- auth/src/main/java/org/openedx/auth/presentation/AgreementProvider.kt
- auth/src/main/java/org/openedx/auth/presentation/AuthRouter.kt
- auth/src/main/java/org/openedx/auth/presentation/signin/SignInFragment.kt
- auth/src/main/java/org/openedx/auth/presentation/signin/SignInUIState.kt
- auth/src/main/java/org/openedx/auth/presentation/signin/SignInViewModel.kt
- auth/src/main/java/org/openedx/auth/presentation/signin/compose/SignInView.kt
- auth/src/main/java/org/openedx/auth/presentation/signup/SignUpFragment.kt
- auth/src/main/java/org/openedx/auth/presentation/signup/SignUpUIState.kt
- auth/src/main/java/org/openedx/auth/presentation/signup/SignUpViewModel.kt
- auth/src/main/java/org/openedx/auth/presentation/signup/compose/SignUpView.kt
- auth/src/main/java/org/openedx/auth/presentation/ui/AuthUI.kt
- auth/src/main/java/org/openedx/auth/presentation/ui/CheckboxField.kt
- auth/src/main/res/values/strings.xml
- auth/src/test/java/org/openedx/auth/presentation/signin/SignInViewModelTest.kt
- auth/src/test/java/org/openedx/auth/presentation/signup/SignUpViewModelTest.kt
- core/src/main/java/org/openedx/core/ApiConstants.kt
- core/src/main/java/org/openedx/core/config/Config.kt
- core/src/main/java/org/openedx/core/domain/model/RegistrationField.kt
- core/src/main/java/org/openedx/core/extension/TextConverter.kt
- core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
What was done:
- Added EULA on Sign in and Sign up screens, if it is presented in the config
- Added Marketing messages checkbox on the sign up screen
> feat: eula on registration and sign in

- core/src/main/java/org/openedx/core/domain/model/Block.kt
- course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerAdapter.kt
- course/src/main/java/org/openedx/course/presentation/unit/video/YoutubeVideoUnitFragment.kt
fixed the crash, where the 'encodedVideos' field is not null, but all fields inside are null.
> fix: crash when trying to open a youtube video when offline

- discussion/src/main/java/org/openedx/discussion/presentation/threads/DiscussionAddThreadFragment.kt
- discussion/src/main/res/values/strings.xml
Changed the name of the button to "Create question" when trying to create a question in a discussion
> fix: changed the button name when trying to create a question

- profile/src/main/java/org/openedx/profile/presentation/edit/EditProfileFragment.kt
Added ability to click on the profile image change icon
> fix: bug when the image change icon was not clickable

- app/src/main/java/org/openedx/app/data/networking/OauthRefreshTokenAuthenticator.kt
- Handle authentication error for email mismatch case
fix: LEARNER-9919
> fix: Add authentication for primary email change through web

- app/src/main/java/org/openedx/app/di/ScreenModule.kt
- discussion/src/main/java/org/openedx/discussion/presentation/topics/DiscussionTopicsFragment.kt
- discussion/src/main/java/org/openedx/discussion/presentation/topics/DiscussionTopicsViewModel.kt
- discussion/src/test/java/org/openedx/discussion/presentation/topics/DiscussionTopicsViewModelTest.kt
fixed a bug when there was no offline panel on the discussions screen
> fix: added the offline panel to the discussions screen

- app/build.gradle
- core/build.gradle
- default_config/dev/config.yaml
- default_config/prod/config.yaml
- default_config/stage/config.yaml
This is a backport of #335 to Redwood.
> Backport of sourceSets dir fallback (#335)

- core/src/main/java/org/openedx/core/module/DownloadWorkerController.kt
- course/src/main/java/org/openedx/course/presentation/download/DownloadDialogManager.kt
- course/src/main/java/org/openedx/course/presentation/offline/CourseOfflineViewModel.kt
Reorganise offline logic for better readability
> Refactor: Offline

- .github/workflows/unit_tests.yml
Issue: https://github.com/openedx/openedx-app-android/issues/400
> build: update action versions
