build.gradle
course/build.gradle
course/src/main/java/org/openedx/course/presentation/unit/video/VideoFullScreenFragment.kt
course/src/main/java/org/openedx/course/presentation/unit/video/VideoUnitFragment.kt
course/src/main/java/org/openedx/course/presentation/unit/video/VideoViewModel.kt
course/src/main/res/layout-w600dp-h480dp/fragment_video_unit.xml
course/src/main/res/layout/fragment_video_full_screen.xml
course/src/main/res/layout/fragment_video_unit.xml

Migrated exoPlayer to media3. A minor change of deprecated logic.

Exoplayer to media3 migration

---

app/proguard-rules.pro

Keep classes that will be serialized/deserialized over Gson in proguard-rules.pro

Gson proguard rules fix

---

core/src/main/java/org/openedx/core/BlockType.kt
core/src/main/java/org/openedx/core/data/model/Block.kt
core/src/main/java/org/openedx/core/data/model/CourseStructureModel.kt
core/src/main/java/org/openedx/core/data/model/room/BlockDb.kt
core/src/main/java/org/openedx/core/data/model/room/CourseStructureEntity.kt
core/src/main/java/org/openedx/core/domain/model/Block.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineFragment.kt
course/src/main/java/org/openedx/course/presentation/section/CourseSectionFragment.kt
course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt
course/src/main/java/org/openedx/course/presentation/videos/CourseVideosFragment.kt
course/src/main/res/drawable/ic_course_block.xml
course/src/test/java/org/openedx/course/presentation/outline/CourseOutlineViewModelTest.kt
course/src/test/java/org/openedx/course/presentation/section/CourseSectionViewModelTest.kt
course/src/test/java/org/openedx/course/presentation/unit/container/CourseUnitContainerViewModelTest.kt
course/src/test/java/org/openedx/course/presentation/videos/CourseVideoViewModelTest.kt

Set the CourseSubsectionItem's icon by highest-priority descendant BlockType. Added sorting of BlockType by priority.

Set CourseSubsectionItem icon by block type

---

app/src/main/java/org/openedx/app/AppRouter.kt
app/src/main/java/org/openedx/app/di/ScreenModule.kt
auth/src/main/java/org/openedx/auth/presentation/AuthRouter.kt
core/src/main/res/values-uk/strings.xml
core/src/main/res/values/strings.xml
discussion/src/main/java/org/openedx/discussion/presentation/DiscussionRouter.kt
discussion/src/main/java/org/openedx/discussion/presentation/comments/DiscussionCommentsFragment.kt
discussion/src/main/java/org/openedx/discussion/presentation/responses/DiscussionResponsesFragment.kt
discussion/src/main/java/org/openedx/discussion/presentation/ui/DiscussionUI.kt
profile/src/main/java/org/openedx/profile/data/model/Account.kt
profile/src/main/java/org/openedx/profile/data/repository/ProfileRepository.kt
profile/src/main/java/org/openedx/profile/domain/interactor/AnothersProfileInteractor.kt
profile/src/main/java/org/openedx/profile/domain/interactor/ProfileInteractor.kt
profile/src/main/java/org/openedx/profile/presentation/anothers_account/AnothersProfileFragment.kt
profile/src/main/java/org/openedx/profile/presentation/anothers_account/AnothersProfileUIState.kt
profile/src/main/java/org/openedx/profile/presentation/anothers_account/AnothersProfileViewModel.kt
profile/src/main/java/org/openedx/profile/presentation/profile/ProfileFragment.kt
profile/src/main/java/org/openedx/profile/presentation/ui/ProfileUI.kt
profile/src/test/java/org/openedx/profile/presentation/profile/AnothersProfileViewModelTest.kt

Added screen of another user profile, with an option to open it from the discussion screen. 
Full name and year of birth are displayed only for staff members.
Below are scenarios of what a profile might look like:
- Learner viewing user profile without bio
- Learner viewing user profile with bio
- Staff user viewing user profile with bio

Discussion's user profile

---

app/src/main/java/org/openedx/app/AnalyticsManager.kt
app/src/main/java/org/openedx/app/di/ScreenModule.kt
build.gradle
core/src/main/java/org/openedx/core/data/api/CourseApi.kt
core/src/main/java/org/openedx/core/data/model/CourseDateBlock.kt
core/src/main/java/org/openedx/core/data/model/CourseDates.kt
core/src/main/java/org/openedx/core/data/model/CourseDatesBannerInfo.kt
core/src/main/java/org/openedx/core/data/model/DateType.kt
core/src/main/java/org/openedx/core/domain/model/CourseDateBlock.kt
core/src/main/java/org/openedx/core/presentation/course/CourseDatesBadge.kt
core/src/main/java/org/openedx/core/ui/theme/Color.kt
core/src/main/java/org/openedx/core/ui/theme/Theme.kt
core/src/main/java/org/openedx/core/utils/TimeUtils.kt
core/src/main/res/values/strings.xml
course/build.gradle
course/src/main/java/org/openedx/course/data/repository/CourseRepository.kt
course/src/main/java/org/openedx/course/domain/interactor/CourseInteractor.kt
course/src/main/java/org/openedx/course/presentation/CourseAnalytics.kt
course/src/main/java/org/openedx/course/presentation/container/CourseContainerFragment.kt
course/src/main/java/org/openedx/course/presentation/container/CourseContainerViewModel.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesViewModel.kt
course/src/main/java/org/openedx/course/presentation/dates/DashboardUIState.kt
course/src/main/res/drawable/ic_calendar_month.xml
course/src/main/res/drawable/ic_lock.xml
course/src/main/res/menu/bottom_course_container_menu.xml
course/src/main/res/values/strings.xml
course/src/test/java/org/openedx/course/presentation/dates/CourseDatesViewModelTest.kt

This PR adds support for Course Dates.
This is a preliminary PR with the Course Dates feature. 
Colors are TBD for both Light and Dark themes.
**Note:**
Not included in this ticket:
- Calendar integration.
- PLS (shift due dates) banner.
- Linking of items on the dates page to specific assessments within the app.
**Sample Video**
https://github.com/openedx/openedx-app-android/assets/43750646/46c0a05f-4f63-436c-a613-6000e2287961

feat: Add support for Course Dates tab

---

docs/0001-strategy-for-data-streams.rst

Added data streams strategy in docs

docs: data streams strategy

---

app/src/main/java/org/openedx/app/data/networking/OauthRefreshTokenAuthenticator.kt
app/src/main/java/org/openedx/app/data/storage/PreferencesManager.kt
app/src/main/java/org/openedx/app/di/NetworkingModule.kt
auth/src/main/java/org/openedx/auth/data/model/AuthResponse.kt
auth/src/main/java/org/openedx/auth/data/repository/AuthRepository.kt
auth/src/main/java/org/openedx/auth/domain/model/AuthResponse.kt
core/src/main/java/org/openedx/core/data/storage/CorePreferences.kt
core/src/main/java/org/openedx/core/utils/TimeUtils.kt

It applies token authentication to the network requests before a network call is made. The expiry duration is saved and it is applied before a network request is queued.
**Authentication:**

feat: Add Token Refresh Implementation to Network Layer

---

core/src/main/java/org/openedx/core/domain/model/Block.kt
course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerAdapter.kt

- Update conditions for components to show only enabled multiview xBlocks on mobile
- Code Improvement: Added Null checks for `studentViewData` for Video and Discussions block 
fix: #85 / LEARNER-9699

fix: show multiView enabled xBlocks on mobile only

---

app/src/main/java/org/openedx/app/AppRouter.kt
core/src/main/java/org/openedx/core/domain/model/CourseStructure.kt
core/src/main/java/org/openedx/core/extension/ListExt.kt
course/src/main/java/org/openedx/course/presentation/CourseRouter.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesViewModel.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineFragment.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineUIState.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineViewModel.kt
course/src/main/java/org/openedx/course/presentation/section/CourseSectionFragment.kt
course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerFragment.kt
course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerViewModel.kt
course/src/main/java/org/openedx/course/presentation/videos/CourseVideosFragment.kt

- Update navigation for the resume component
- Code improvement & optimization
| Current implementation  | New Implementation |
| ------------- | ------------- |
| When the user taps on the resume course, it navigates to the `subSection` screen.  | The user will navigate to the last visited component   |
| <video src="https://github.com/openedx/openedx-app-android/assets/30689349/79453509-f7ce-44ba-ad3b-6bd00737962b" />  |<video src="https://github.com/openedx/openedx-app-android/assets/30689349/74630fa1-59d4-490a-a0ff-6fd812084489"/>  |

fix: Update resume course navigation

---

app/src/main/java/org/openedx/app/AnalyticsManager.kt
app/src/main/java/org/openedx/app/di/AppModule.kt
core/src/main/java/org/openedx/core/config/AgreementUrlsConfig.kt
core/src/main/java/org/openedx/core/config/Config.kt
core/src/main/java/org/openedx/core/domain/model/AgreementUrls.kt
core/src/main/java/org/openedx/core/presentation/global/AppData.kt
core/src/main/java/org/openedx/core/presentation/global/webview/WebContentFragment.kt
core/src/main/res/values/strings.xml
default_config/dev/config.yaml
default_config/prod/config.yaml
default_config/stage/config.yaml
profile/src/main/java/org/openedx/profile/domain/model/Configuration.kt
profile/src/main/java/org/openedx/profile/presentation/ProfileAnalytics.kt
profile/src/main/java/org/openedx/profile/presentation/profile/ProfileFragment.kt
profile/src/main/java/org/openedx/profile/presentation/profile/ProfileUIState.kt
profile/src/main/java/org/openedx/profile/presentation/profile/ProfileViewModel.kt
profile/src/main/java/org/openedx/profile/presentation/profile/compose/ProfileView.kt
profile/src/test/java/org/openedx/profile/presentation/profile/ProfileViewModelTest.kt

Configuration fields added:
```
AGREEMENT_URLS:
PRIVACY_POLICY_URL: ''
COOKIE_POLICY_URL: ''
DATA_SELL_CONSENT_URL: ''
TOS_URL: ''
EULA_URL: ''
SUPPORTED_LANGUAGES: [ ] #en is defalut language
```
For `SUPPORTED_LANGUAGES` we are adding lang to the url path
If configuration field is empty, button will be hided in profile.
https://github.com/openedx/openedx-app-android/assets/1063094/28b55327-05d5-49a9-9d17-03e2378393ac

feat: agreement urls

---

auth/src/main/java/org/openedx/auth/presentation/restore/RestorePasswordFragment.kt
auth/src/main/java/org/openedx/auth/presentation/signin/SignInViewModel.kt
auth/src/main/java/org/openedx/auth/presentation/signin/compose/SignInView.kt
auth/src/main/java/org/openedx/auth/presentation/ui/AuthUI.kt
auth/src/main/res/values/strings.xml
auth/src/test/java/org/openedx/auth/presentation/signin/SignInViewModelTest.kt
core/src/main/java/org/openedx/core/Validator.kt

- Add `username` support for the authentication.
- User can log in using email.
**Before** | **After** |
--- | --- |
| ![Screenshot_20240110_191406](https://github.com/openedx/openedx-app-android/assets/43750646/5e16660f-01b8-4269-a89a-42ff3695dde4) | ![Screenshot_20240110_190659](https://github.com/openedx/openedx-app-android/assets/43750646/7c5d9d13-51bf-493c-9e58-03b688decc78) |

feat: Login through username in the new app

---

app/src/main/java/org/openedx/app/di/ScreenModule.kt
auth/src/main/java/org/openedx/auth/presentation/logistration/LogistrationFragment.kt
auth/src/main/java/org/openedx/auth/presentation/restore/RestorePasswordFragment.kt
auth/src/main/java/org/openedx/auth/presentation/signin/compose/SignInView.kt
auth/src/main/java/org/openedx/auth/presentation/signup/SignUpFragment.kt
auth/src/main/java/org/openedx/auth/presentation/ui/AuthUI.kt
core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
whatsnew/src/main/java/org/openedx/whatsnew/presentation/ui/WhatsNewUI.kt
whatsnew/src/main/java/org/openedx/whatsnew/presentation/whatsnew/WhatsNewFragment.kt
whatsnew/src/main/java/org/openedx/whatsnew/presentation/whatsnew/WhatsNewViewModel.kt

Add IDs to elements of landing, login, register, and what's new screens.
**Landing Screen:**
- The title under the App logo (Courses and programs from the world's best universities in your pocket)
- Text: (What do you want to learn?)
- Textfield (Search our 3000+ courses)
- Button: (Explore all courses)
- Button: Register
- Button: Sign in
**Login Screen:**
- Title: (Sign In)
- Text: (Welcome back! Please authorize to continue.)
- Email and Password (Labels and TextFields)
- Button: (Forgot password?)
- Button (Sign In)
- Text: (Or sign in with:)
- Buttons: (Sign in with Google, Facebook, Microsoft and Apple)
- On Forgot password page (Title, Text, Email label, Email field and Reset password button)
**Register Screen:**
- Title: (Sign up)
- Text: (Create new account.)
- All Input Fields …

refactor: Add IDs to elements of landing, login, register, and what's new screens

---

core/src/main/java/org/openedx/core/data/api/CourseApi.kt
core/src/main/java/org/openedx/core/data/model/CourseDates.kt
core/src/main/java/org/openedx/core/data/model/CourseDatesBannerInfo.kt
core/src/main/java/org/openedx/core/domain/model/CourseDatesBannerInfo.kt
core/src/main/res/values/strings.xml
course/src/main/java/org/openedx/course/data/repository/CourseRepository.kt
course/src/main/java/org/openedx/course/domain/interactor/CourseInteractor.kt
course/src/main/java/org/openedx/course/presentation/container/CourseContainerAdapter.kt
course/src/main/java/org/openedx/course/presentation/container/CourseContainerFragment.kt
course/src/main/java/org/openedx/course/presentation/container/CourseContainerViewModel.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesViewModel.kt
course/src/main/java/org/openedx/course/presentation/info/CourseInfoFragment.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineFragment.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineUIState.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineViewModel.kt
course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt
course/src/main/res/menu/bottom_course_container_menu.xml
course/src/test/java/org/openedx/course/presentation/outline/CourseOutlineViewModelTest.kt
dashboard/src/main/java/org/openedx/dashboard/presentation/program/ProgramFragment.kt

- Banner added on course dashboard if its type is RESET_DATES and the course is still accessible.

feat: added PLS banner for shift dates on Course Dashboard

---

app/src/main/java/org/openedx/app/AppRouter.kt
app/src/main/java/org/openedx/app/MainFragment.kt
app/src/main/java/org/openedx/app/di/ScreenModule.kt
auth/src/main/java/org/openedx/auth/presentation/AuthRouter.kt
auth/src/main/java/org/openedx/auth/presentation/logistration/LogistrationFragment.kt
auth/src/main/java/org/openedx/auth/presentation/signin/SignInFragment.kt
auth/src/main/java/org/openedx/auth/presentation/signin/SignInViewModel.kt
auth/src/main/java/org/openedx/auth/presentation/signup/SignUpFragment.kt
auth/src/main/java/org/openedx/auth/presentation/signup/SignUpViewModel.kt
auth/src/test/java/org/openedx/auth/presentation/signin/SignInViewModelTest.kt
auth/src/test/java/org/openedx/auth/presentation/signup/SignUpViewModelTest.kt
core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
core/src/main/java/org/openedx/core/utils/UrlUtils.kt
course/src/main/java/org/openedx/course/presentation/CourseRouter.kt
course/src/main/java/org/openedx/course/presentation/detail/CourseDetailsFragment.kt
course/src/main/java/org/openedx/course/presentation/info/CourseInfoFragment.kt
course/src/main/java/org/openedx/course/presentation/info/CourseInfoUIState.kt
course/src/main/java/org/openedx/course/presentation/info/CourseInfoViewModel.kt
discovery/src/main/java/org/openedx/discovery/presentation/DiscoveryNavigator.kt
discovery/src/main/java/org/openedx/discovery/presentation/DiscoveryRouter.kt
discovery/src/main/java/org/openedx/discovery/presentation/NativeDiscoveryFragment.kt
discovery/src/main/java/org/openedx/discovery/presentation/WebViewDiscoveryFragment.kt
discovery/src/main/java/org/openedx/discovery/presentation/WebViewDiscoveryViewModel.kt
discovery/src/main/java/org/openedx/discovery/presentation/search/CourseSearchFragment.kt
whatsnew/src/main/java/org/openedx/whatsnew/WhatsNewRouter.kt
whatsnew/src/main/java/org/openedx/whatsnew/presentation/whatsnew/WhatsNewFragment.kt
whatsnew/src/main/java/org/openedx/whatsnew/presentation/whatsnew/WhatsNewViewModel.kt
whatsnew/src/test/java/org/openedx/whatsnew/WhatsNewViewModelTest.kt

- Integrate search to align with configured discovery settings.
- “Explore All Courses" redirects based on the feature discovery flag.
- Auth Panel (SignIn, Register) remains visible during pre-login WebView discovery.
- Ensure Sign In & Enroll mirror Native Discovery & Market App functionality.
[Screen_recording_20240201_162216.webm](https://github.com/openedx/openedx-app-android/assets/43750646/b09e7856-c2e8-4e61-94eb-4718d5ac8d22)

feat: Pre-Login Experience enhancement by integrating webview discovery

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/openedx/app/AppActivity.kt
app/src/main/java/org/openedx/app/AppViewModel.kt
app/src/main/java/org/openedx/app/OpenEdXApp.kt
core/src/main/java/org/openedx/core/config/BranchConfig.kt
core/src/main/java/org/openedx/core/config/Config.kt
core/src/main/java/org/openedx/core/utils/Logger.kt
default_config/dev/config.yaml
default_config/prod/config.yaml
default_config/stage/config.yaml

This PR adds the integration of the [Branch SDK](https://branch.io/). The Branch SDK will be used for deep links.
```
BRANCH:
ENABLED: false
KEY: ''
URI_SCHEME: ''
HOST: ''
ALTERNATE_HOST: ''
```
- https://help.branch.io/developers-hub/docs/android-basic-integration

feat: Branch SDK Integration

---

core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
core/src/main/java/org/openedx/core/ui/WebContentScreen.kt

- Adjust padding and text on the toolbar
- Remove padding from WebContentScreen
| Old Implementation   | New Implementation  |
| ------------- | ------------- |
| <Img src="https://github.com/openedx/openedx-app-android/assets/30689349/ebab3645-a57f-4bdc-ad8d-50ab5ace6c98" height=480/>  |<Img src="https://github.com/openedx/openedx-app-android/assets/30689349/2f53ea4a-a586-4f46-9354-1a6f77a03a2e" height=480/>  |

fix: Adjust padding on WebContentScreen

---

core/src/main/java/org/openedx/core/ui/WebContentScreen.kt

Fixed the next bug:
it occurred due to the inability to update the URL in the WebView

fix: bug when data is not displayed on the Hangouts and Announcement

---

auth/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

PR includes updates to project dependencies and introduces a workaround for com.microsoft.identity.client:msal for AS Iguana.
Gradle 8.0 -> 8.4
Kotlin 1.8.21 -> 1.9.22
Compose 1.5.0 -> 1.6.2
Compose Compiler 1.4.7 -> 1.5.10
Material 1.9.0 -> 1.11.0
Lifecycle 2.6.1 -> 2.7.0
Fragment 1.6.1 -> 1.6.2
Room 2.5.2 -> 2.6.1
WorkManager 2.8.1 -> 2.9.0
Window 1.1.0 -> 1.2.0
play-services-auth 20.7.0 -> 21.0.0

chore: Update dependency versions

---

course/src/main/java/org/openedx/course/presentation/ChapterEndFragmentDialog.kt
course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerFragment.kt

There is an issue on Android where 'Fragment.onDestroy()' is not called after one fragment was replaced with another using the 'FragmentManager.replace()' function without 'addToBackStack()'. And after a long discussion with @volodymyr-chekyrta we decided to make a workaround for this issue.
All new CourseUnitContainerFragment instances will be added with 'addToBackStack()' and then to go to the previous fragment we need to find it and call 'popBackStack(previousFragmentTagName)'.
Using this workaround, also, was fixed a bug where the 'Back to outline' button would not work.

fix: bug when video continues to play when exiting content

---

Documentation/APIs_Compatibility.md
Documentation/ConfigurationManagement.md
README.md

This PR updates the project README file, introduces documentation on configuration management and APIs compatibility.

docs: Update project documentation

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/openedx/app/OpenEdXApp.kt
core/src/main/java/org/openedx/core/config/FirebaseConfig.kt
settings.gradle

This PR expands Braze's capabilities to seamlessly receive Push Notifications directly from the Braze Dashboard.
To achieve this, integration of the Firebase Cloud Messaging (FCM) SDK is necessary, along with registering the Firebase service.
- [Segment-Braze Integration](https://segment.com/docs/connections/destinations/catalog/braze/#android)
- [Braze Push Notification Integration](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration/)

feat: Braze Push Notifications Capabilities

---

app/src/main/java/org/openedx/app/di/ScreenModule.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesViewModel.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineFragment.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineViewModel.kt
course/src/test/java/org/openedx/course/presentation/dates/CourseDatesViewModelTest.kt

Removed sequence units level when open a content from Resume or Dates

fix: bug when sequence units level appear after tapping back

---

app/src/main/java/org/openedx/app/di/ScreenModule.kt
discussion/src/main/java/org/openedx/discussion/data/repository/DiscussionRepository.kt
discussion/src/main/java/org/openedx/discussion/domain/model/TopicsData.kt
discussion/src/main/java/org/openedx/discussion/presentation/ui/DiscussionUI.kt
discussion/src/main/res/values/strings.xml

fixed a bug when the name of subcategory was empty in Discussions

fix: bug when the name of subcategory is empty

---

core/src/main/java/org/openedx/core/ui/ComposeCommon.kt

This pull request addresses the toolbar text alignment issue caused by earlier pull requests.
According to Open edX mobile design, all titles should be centered aligned.

Fix: toolbar alignment

---

core/src/main/java/org/openedx/core/UIMessage.kt
core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
core/src/main/res/values/strings.xml
course/src/main/java/org/openedx/course/DatesShiftedSnackBar.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesFragment.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesViewModel.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineFragment.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineViewModel.kt
course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt
course/src/main/res/values/strings.xml

- Dates Tab Shift Due Dates Success SnackBar Design Changes
Jira: [LEARNER-9868](https://2u-internal.atlassian.net/browse/LEARNER-9868)
Github issue: [[Android] Shift Dates (PLS) Design Changes](https://github.com/openedx/openedx-app-android/issues/240)
| Old | New |
| ------------- | ------------- |
| ![Screenshot_20240320_155845](https://github.com/openedx/openedx-app-android/assets/43750646/5b368d1a-b180-46fb-b278-a71a8445c966) | ![Screenshot_20240320_155406](https://github.com/openedx/openedx-app-android/assets/43750646/1dc07383-c2a9-4ba8-ab4e-f261f231870e) |

style: Dates Tab Shift Due Dates Success SnackBar Design Changes

---

course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineFragment.kt
course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt

Removed extra space on the course tab in different scenarios like: with/without new design, with/without resume button, with/without Dates banner.

fix: removed extra space on the course tab

---

discovery/src/main/java/org/openedx/discovery/presentation/NativeDiscoveryFragment.kt
discovery/src/main/java/org/openedx/discovery/presentation/WebViewDiscoveryFragment.kt
discovery/src/main/java/org/openedx/discovery/presentation/info/CourseInfoFragment.kt
discovery/src/main/java/org/openedx/discovery/presentation/program/ProgramFragment.kt

Discover, Program and Explore all courses screens now appear in the middle on tablets

fix: a bug when Discover and Program screens appear not in the middle

---

course/src/main/java/org/openedx/course/presentation/calendarsync/CalendarManager.kt

Enhances calendar events comparison for migration by ignoring seconds, and milliseconds improving compatibility with the new codebase. Previously, seconds and milliseconds were not considered. Calendar events and course date blocks have seconds and milliseconds set to zero for precise matching, ensuring a smooth transition.

refactor: Enhance calendar event comparison for migration

---

catalog-info.yaml

Adding `catalog-info.yaml` according to [OEP-55](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html).

chore: add maintainership documentation

---

core/src/main/java/org/openedx/core/ui/ComposeExtensions.kt

Modifier factory functions must use the receiver Modifier instance.
`Inspection info:` Modifier factory functions are fluently chained to construct a chain of Modifier objects that will be applied to a layout. As a result, each factory function must use the receiver Modifier parameter, to ensure that the function is returning a chain that includes previous items in the chain. Make sure the returned chain either explicitly includes this, such as return this.then(MyModifier) or implicitly by returning a chain that starts with an implicit call to another factory function, such as return myModifier(), where myModifier is defined as fun Modifier.myModifier(): Modifier.

fix: Modifier.noRippleClickable Modifier factory error

---

.github/workflows/unit_tests.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Gradle was updated from 8.4 to 8.6, and the Android Gradle plugin was updated from 8.3 to 8.4 according to the AS Jellyfish release.
Note: `java.lang.OutOfMemoryError` still appears on rebuild.
Workaround: change locally `org.gradle.jvmargs=-Xmx2048m` to a required value.

chore: Upgrade AGP 8.3 -> 8.4

---

Documentation/ConfigurationManagement.md
README.md
default_config/dev/config.yaml
default_config/prod/config.yaml
default_config/stage/config.yaml

Fix typos in the documentation and config files

fix: typos

---

app/src/main/java/org/openedx/app/di/ScreenModule.kt
core/src/main/java/org/openedx/core/system/notifier/CourseDataReady.kt
core/src/main/java/org/openedx/core/system/notifier/CourseNotifier.kt
course/src/main/java/org/openedx/course/data/repository/CourseRepository.kt
course/src/main/java/org/openedx/course/domain/interactor/CourseInteractor.kt
course/src/main/java/org/openedx/course/presentation/container/CourseContainerFragment.kt
course/src/main/java/org/openedx/course/presentation/container/CourseContainerViewModel.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesViewModel.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineViewModel.kt
course/src/main/java/org/openedx/course/presentation/section/CourseSectionViewModel.kt
course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerFragment.kt
course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerViewModel.kt
course/src/main/java/org/openedx/course/presentation/videos/CourseVideoViewModel.kt
course/src/test/java/org/openedx/course/presentation/container/CourseContainerViewModelTest.kt
course/src/test/java/org/openedx/course/presentation/dates/CourseDatesViewModelTest.kt
course/src/test/java/org/openedx/course/presentation/outline/CourseOutlineViewModelTest.kt
course/src/test/java/org/openedx/course/presentation/section/CourseSectionViewModelTest.kt
course/src/test/java/org/openedx/course/presentation/unit/container/CourseUnitContainerViewModelTest.kt
course/src/test/java/org/openedx/course/presentation/videos/CourseVideoViewModelTest.kt
discussion/src/main/java/org/openedx/discussion/presentation/topics/DiscussionTopicsScreen.kt
discussion/src/main/java/org/openedx/discussion/presentation/topics/DiscussionTopicsViewModel.kt
discussion/src/test/java/org/openedx/discussion/presentation/topics/DiscussionTopicsViewModelTest.kt

Changed the way course data is loaded.
Previously there was the preloadCourseStructure function that was called when we opened a course. Then all data was cached and used in other places such as open content and etc. When the app was in the background for a long time all the data was cleared by the system and if the user tries to open the app - it crashes. 
I changed the way the Course Structure is retrieved and added a check for empty data.
https://github.com/openedx/openedx-app-android/issues/139

fix: crash when restoring the app after a long period of inactivity

---

core/src/main/java/org/openedx/core/config/Config.kt
core/src/main/java/org/openedx/core/config/ProgramConfig.kt
core/src/main/java/org/openedx/core/config/UIConfig.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesViewModel.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineViewModel.kt
course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt
course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerViewModel.kt
course/src/main/java/org/openedx/course/presentation/unit/html/HtmlUnitViewModel.kt
course/src/main/java/org/openedx/course/presentation/videos/CourseVideoViewModel.kt
course/src/test/java/org/openedx/course/presentation/outline/CourseOutlineViewModelTest.kt
course/src/test/java/org/openedx/course/presentation/videos/CourseVideoViewModelTest.kt
dashboard/src/main/java/org/openedx/dashboard/presentation/DashboardListFragment.kt
default_config/dev/config.yaml
default_config/prod/config.yaml
default_config/stage/config.yaml
discovery/src/main/java/org/openedx/discovery/presentation/ui/DiscoveryUI.kt

- Update dictionary for ProgramConfig
- Update UI related feature flags under a single Key
- fix image load in course
fix: Issue-[318](https://github.com/openedx/openedx-app-android/issues/318)

fix: update config parsing structure

---

app/src/main/java/org/openedx/app/AppActivity.kt
app/src/main/java/org/openedx/app/AppViewModel.kt
app/src/main/java/org/openedx/app/data/storage/PreferencesManager.kt
app/src/main/java/org/openedx/app/di/ScreenModule.kt
app/src/test/java/org/openedx/AppViewModelTest.kt
core/src/main/java/org/openedx/core/data/storage/CorePreferences.kt
core/src/main/java/org/openedx/core/utils/FileUtil.kt
dashboard/src/main/java/org/openedx/dashboard/presentation/DashboardListFragment.kt
dashboard/src/main/java/org/openedx/dashboard/presentation/DashboardListViewModel.kt

This PR implements functionality to delete outdated video files stored in the previous app directory upon the first launch of the updated app version. This ensures that storage is efficiently managed, preventing unnecessary space usage by obsolete files, and maintaining consistency with the new data storage structure.
fix: LEARNER-9950

feat: delete old videos Directory

---

course/src/main/java/org/openedx/course/presentation/container/CollapsingLayout.kt

- added content description for views
- make list as default view for MainDashboard
fix: LEARNER-10021

fix: Accessibility issue on courseDashboard

---

app/src/main/java/org/openedx/app/AppRouter.kt
app/src/main/java/org/openedx/app/MainFragment.kt
app/src/main/java/org/openedx/app/MainViewModel.kt
dashboard/src/main/java/org/openedx/DashboardNavigator.kt
dashboard/src/main/java/org/openedx/dashboard/presentation/DashboardListFragment.kt
dashboard/src/main/java/org/openedx/dashboard/presentation/DashboardRouter.kt
dashboard/src/main/java/org/openedx/learn/presentation/LearnFragment.kt
dashboard/src/main/java/org/openedx/learn/presentation/LearnViewModel.kt
dashboard/src/main/res/values-uk/strings.xml
dashboard/src/main/res/values/strings.xml
discovery/src/main/java/org/openedx/discovery/presentation/program/ProgramFragment.kt

- Update/optimize ProgramFragment
- enable ProgramFragment for both dashboards(list/gallery)
- added InDevelopmentFragment if programs not available.
Design: https://www.figma.com/design/iZ56YMjbRMShCCDxqrqRrR/Open-edX-Mobile-App-All-Screens-v2.1?node-id=16217-63561&t=kdCxIN8hh0ZOch7C-0
|Learn(only courses as List)|Learn(Courses(list)+Programs)|
|-----|-----|
|<img width="420" alt="Learn_courses_list" src="https://github.com/openedx/openedx-app-android/assets/30689349/a7e4b89f-dbc5-489f-bc83-54e7d2550379"> | <video width="420" alt="List_programs" src="https://github.com/openedx/openedx-app-android/assets/30689349/6e3cd03c-5b9c-4ebd-baa0-83d0bafbfb30">|
|Learn(only courses as Gallery)|Learn(Courses(gallery)+Programs)|
|--------|-------|
|<img width="420" alt="Learn_courses_gallery" …

fix: enable Programs view for new dashboard navigation

---

course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineScreen.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineViewModel.kt
course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt
course/src/main/java/org/openedx/course/presentation/ui/CourseVideosUI.kt

- Added filtering of block IDs before download
- Performed minor refactoring
| Before | After |
| --------- | --------- |
| https://github.com/openedx/openedx-app-android/assets/71447999/3d381757-ab24-49a5-a108-fcf87a67a416 | https://github.com/openedx/openedx-app-android/assets/141041606/de6b02e6-3af1-463e-a01a-aca7b7c9d51a |

fix: Video downloading bug

---

app/build.gradle
core/build.gradle
default_config/dev/config.yaml
default_config/prod/config.yaml
default_config/stage/config.yaml

This PR introduces a fallback for the sourceSets directory.
This fallback is aimed at fixing an issue with the Tutor build.

fix: sourceSets dir fallback

---

dashboard/src/main/java/org/openedx/dashboard/presentation/DashboardListFragment.kt

- Replace the fragmentManager of parentFragment with activity
[Issue: 325](https://github.com/openedx/openedx-app-android/issues/325)

 fix: Crash on opening a course from DashboardListFragment 

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/openedx/app/AppActivity.kt
app/src/main/java/org/openedx/app/AppRouter.kt
app/src/main/java/org/openedx/app/AppViewModel.kt
app/src/main/java/org/openedx/app/MainFragment.kt
app/src/main/java/org/openedx/app/deeplink/DeepLink.kt
app/src/main/java/org/openedx/app/deeplink/DeepLinkRouter.kt
app/src/main/java/org/openedx/app/deeplink/HomeTab.kt
app/src/main/java/org/openedx/app/deeplink/Screen.kt
app/src/main/java/org/openedx/app/di/AppModule.kt
app/src/main/java/org/openedx/app/di/ScreenModule.kt
app/src/test/java/org/openedx/AppViewModelTest.kt
auth/src/main/java/org/openedx/auth/presentation/AuthRouter.kt
course/src/main/java/org/openedx/course/presentation/CourseRouter.kt
course/src/main/java/org/openedx/course/presentation/container/CourseContainerFragment.kt
course/src/main/java/org/openedx/course/presentation/handouts/HandoutsWebViewFragment.kt
dashboard/src/main/java/org/openedx/learn/presentation/LearnFragment.kt
dashboard/src/main/java/org/openedx/learn/presentation/LearnTab.kt
discovery/src/main/java/org/openedx/discovery/presentation/detail/CourseDetailsFragment.kt
discovery/src/main/java/org/openedx/discovery/presentation/info/CourseInfoViewModel.kt
discussion/src/main/java/org/openedx/discussion/data/api/DiscussionApi.kt
discussion/src/main/java/org/openedx/discussion/data/repository/DiscussionRepository.kt
discussion/src/main/java/org/openedx/discussion/domain/interactor/DiscussionInteractor.kt
whatsnew/src/main/java/org/openedx/whatsnew/WhatsNewRouter.kt
whatsnew/src/main/java/org/openedx/whatsnew/presentation/whatsnew/WhatsNewViewModel.kt

Added ability to redirect from deep links/push notifications to different screens.
https://github.com/openedx/openedx-app-android/assets/5153976/ffaaee16-665d-46c4-97fb-38075876223e

feat: added the external router for deep links

---

app/build.gradle
core/build.gradle
core/src/main/java/org/openedx/core/presentation/settings/calendarsync/CalendarSyncUIState.kt
core/src/main/java/org/openedx/core/system/CalendarManager.kt
course/src/main/java/org/openedx/course/presentation/container/CourseContainerViewModel.kt

Add deep links to related course content in the calendar events to make it easier for learners to access them. 
https://github.com/openedx/openedx-app-android/assets/71447999/1d06b84d-2c09-4110-af67-352812de798a

feat: Add Branch deep links to local calendar events

---

.gitignore
Makefile
README.md
i18n_scripts/requirements.txt
i18n_scripts/translation.py

This pull request provides the CI scripts and developer tooling for the [Atlas Translations Management Design
](https://github.com/openedx/openedx-app-ios/blob/develop/docs/0002-atlas-translations-management.rst) proposal related to [OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).
```
make ATLAS_OPTIONS='--repository=Zeit-Labs/openedx-translations --revision=fc_55_sample' pull_translations
```
1) The None-English translations will be pulled from openedx-translations repo into `I18N/` directory.
2) Then each language file will be split and distributed to the modules one by one
3) In the end, the pulled translations will be removed and only the split translations can be found in the modules' directories
1) The above command should not produce errors when …

feat: atlas push pull scripts: FC-55

---

discovery/src/main/res/values/strings.xml
discussion/src/main/res/values/strings.xml

Transifex throws a validation error otherwise.
In other languages Transifex will provide the proper plurals.

fix: English plurals error in transifex should be `one` and `other` | FC-55

---

app/src/main/java/org/openedx/app/di/ScreenModule.kt
dashboard/src/main/java/org/openedx/courses/presentation/DashboardGalleryView.kt
dashboard/src/main/java/org/openedx/courses/presentation/DashboardGalleryViewModel.kt
dashboard/src/main/java/org/openedx/dashboard/data/repository/DashboardRepository.kt
dashboard/src/main/java/org/openedx/dashboard/domain/interactor/DashboardInteractor.kt

The view all button must appear when a user is enrolled in more than 5 courses (mobile) and 7 for tablet.

fix: dashboard view all button

---

.github/workflows/validate-english-strings.yml
Makefile
core/src/main/res/values/strings.xml
course/src/main/res/values/strings.xml
dashboard/src/main/res/values/strings.xml

Plurals are failing the transifex import. I've fixed them manually in #341, but more are coming. Therefore a GitHub Actions is needed.
Example failure:
- https://github.com/openedx/openedx-app-android/actions/runs/9610916922/job/26508405063#step:5:33
```
core/src/main/res/values/strings.xml:        <item quantity="zero">Due %1$d days ago</item>
core/src/main/res/values/strings.xml:        <item quantity="two">Due %1$d days ago</item>
make: *** [Makefile:15: validate_english_plurals] Error 1
core/src/main/res/values/strings.xml:        <item quantity="few">Due %1$d days ago</item>
core/src/main/res/values/strings.xml:        <item quantity="many">Due %1$d days ago</item>
core/src/main/res/values/strings.xml:        <item quantity="zero">Due in %1$d days</item> …
```

chore: validate plurals in strings.xml | FC-55

---

auth/src/main/java/org/openedx/auth/presentation/restore/RestorePasswordFragment.kt
auth/src/main/java/org/openedx/auth/presentation/signin/compose/SignInView.kt
auth/src/main/java/org/openedx/auth/presentation/signup/compose/SignUpView.kt
auth/src/main/java/org/openedx/auth/presentation/ui/AuthUI.kt
auth/src/main/res/values/strings.xml
discussion/src/main/java/org/openedx/discussion/presentation/threads/DiscussionAddThreadFragment.kt
profile/src/main/java/org/openedx/profile/presentation/edit/EditProfileFragment.kt

- Hide keyboard on logistration screens
- update imeAction for long InputEditFields
- Added errors for empty fields on SignInScreen & Restore Password Screen
-LEARNER-10032
<Img src="https://github.com/openedx/openedx-app-android/assets/30689349/90654a16-9704-467f-a8f7-40dc82d34575" height="420"/>

fix: update keyboard visibility and imeAction

---

course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineViewModel.kt
course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt
course/src/main/java/org/openedx/course/presentation/videos/CourseVideoViewModel.kt

Consolidated the progress screens into a single screen that lists all ongoing downloads, mirroring the interface used for bulk downloads.

fix: show only one screen with all downloadable content

---

course/src/main/java/org/openedx/course/presentation/ui/CourseUI.kt
course/src/main/java/org/openedx/course/presentation/unit/video/VideoUnitFragment.kt
course/src/main/java/org/openedx/course/presentation/unit/video/VideoUnitViewModel.kt
course/src/main/java/org/openedx/course/presentation/unit/video/VideoViewModel.kt

The video subtitles weren't working because the handler was deleted.

fix: Video Subtitles on Native and Youtube Player

---

app/src/main/java/org/openedx/app/AppActivity.kt
app/src/main/java/org/openedx/app/OpenEdXApp.kt
app/src/main/java/org/openedx/app/deeplink/BranchBrazeDeeplinkHandler.kt
app/src/main/java/org/openedx/app/deeplink/BrazeBranchDeeplinkHandler.kt

To manage branch deeplinks arriving in Braze push notifications
https://github.com/openedx/openedx-app-android/assets/71447999/dc93a742-9015-4b98-baac-ab396275fbb7
- [Braze Deeplink Handler](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking/#universal-deep-link-delegate)

feat: Handle Branch Deeplinks from Braze Push Notification

---

app/src/main/java/org/openedx/app/data/storage/PreferencesManager.kt
core/src/main/java/org/openedx/core/domain/model/AppConfig.kt

**Fix based on the crash report:**
```
PreferencesManager.getAppConfig
Caused by java.lang.NullPointerException: fromJson(...) must not be null
at org.openedx.app.data.storage.PreferencesManager.getAppConfig(PreferencesManager.kt:20)
at org.openedx.profile.presentation.settings.SettingsViewModel.getConfiguration(SourceFile:7)
at org.openedx.profile.presentation.settings.SettingsViewModel.<init>(SourceFile:32)
at org.openedx.app.di.ScreenModuleKt$screenModule$1$28.invoke(ScreenModule.kt:193)
at org.openedx.app.di.ScreenModuleKt$screenModule$1$28.invoke(ScreenModule.kt:193)
at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:53)
```
**Steps to reproduce:**
- Fresh install app
- Login into app
- See What's new
- Turn off internet connection
- Go to profile and open settings
- …

fix: added default value to the AppConfig to prevent crashes in some cases

---

app/src/main/java/org/openedx/app/AppRouter.kt

Added ability to ignore crash when we try to add a fragment at the wrong time. This doesn't affect anything and works when the app in the background state.

fix: ignore IllegalStateException when fragment transaction fails

---

dashboard/src/main/java/org/openedx/dashboard/presentation/DashboardListFragment.kt
dashboard/src/main/res/values/strings.xml

In the main branch of the app it isn't possible to refresh the course list when there are no courses listed, since pull to refresh can only be triggered when a container is scrollable. This makes the empty container scrollable to allow it to trigger a pull to refresh action. 
This change was originally made for the main branch; however, it seems that the develop version has changed significantly enough that this may no longer be needed. The files for the old UI are still there, though, so perhaps there are situations where it's still used, and this PR would be useful? If not, feel free to close the PR.

fix: Support pull to refresh for empty dashboard

---

course/src/main/java/org/openedx/course/presentation/unit/container/CourseUnitContainerAdapter.kt

- Going forward, all HTML Xblocks will be visible on the mobile side, regardless of `student_view_multi_device`.
fix: LEARNER-10232

fix: Remove student_view_mutli_device dependency for HTML XBlocks

---

Documentation/ConfigurationManagement.md
auth/src/main/java/org/openedx/auth/presentation/logistration/LogistrationFragment.kt
auth/src/main/java/org/openedx/auth/presentation/logistration/LogistrationViewModel.kt
auth/src/main/java/org/openedx/auth/presentation/signin/SignInUIState.kt
auth/src/main/java/org/openedx/auth/presentation/signin/SignInViewModel.kt
auth/src/main/java/org/openedx/auth/presentation/signin/compose/SignInView.kt
auth/src/test/java/org/openedx/auth/presentation/signin/SignInViewModelTest.kt
core/src/main/java/org/openedx/core/config/Config.kt
core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
default_config/dev/config.yaml
default_config/prod/config.yaml
default_config/stage/config.yaml
discovery/src/main/java/org/openedx/discovery/presentation/NativeDiscoveryFragment.kt
discovery/src/main/java/org/openedx/discovery/presentation/NativeDiscoveryViewModel.kt
discovery/src/main/java/org/openedx/discovery/presentation/WebViewDiscoveryFragment.kt
discovery/src/main/java/org/openedx/discovery/presentation/WebViewDiscoveryViewModel.kt
discovery/src/main/java/org/openedx/discovery/presentation/detail/CourseDetailsFragment.kt
discovery/src/main/java/org/openedx/discovery/presentation/detail/CourseDetailsViewModel.kt
discovery/src/main/java/org/openedx/discovery/presentation/info/CourseInfoFragment.kt
discovery/src/main/java/org/openedx/discovery/presentation/info/CourseInfoViewModel.kt
discovery/src/main/java/org/openedx/discovery/presentation/search/CourseSearchFragment.kt
discovery/src/main/java/org/openedx/discovery/presentation/search/CourseSearchViewModel.kt

Some OpenedX operators want user registration disabled from their UIs, so that user registration can be operated through the APIs, from external applications like salesforce. Currently we don't have such an option for this android app.
This PR adds a flag called `REGISTRATION_ENABLED` which controls if Registration option is displayed to users.
1. Checkout and setup this branch
2. Set `REGISTRATION_ENABLED` to `true` in config and verify Registration button/link is visible.
3. Set `REGISTRATION_ENABLED` to `false` in config and verify Registration button/link is gone.
Private Ref : [BB-9186](https://tasks.opencraft.com/browse/BB-9186)

feat: add flag to remove registration from app

---

dashboard/src/main/java/org/openedx/courses/presentation/DashboardGalleryView.kt
dashboard/src/main/java/org/openedx/courses/presentation/DashboardGalleryViewModel.kt

Added ability to update the primary course on the learn tab automatically

feat: added ability update the primary course on the learn tab

---

core/src/main/java/org/openedx/core/NoContentScreenType.kt
core/src/main/java/org/openedx/core/ui/ComposeCommon.kt
core/src/main/java/org/openedx/core/ui/WebContentScreen.kt
core/src/main/res/drawable/core_ic_no_announcements.xml
core/src/main/res/drawable/core_ic_no_content.xml
core/src/main/res/drawable/core_ic_no_handouts.xml
core/src/main/res/drawable/core_ic_no_videos.xml
core/src/main/res/values/strings.xml
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesScreen.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesUIState.kt
course/src/main/java/org/openedx/course/presentation/dates/CourseDatesViewModel.kt
course/src/main/java/org/openedx/course/presentation/dates/DashboardUIState.kt
course/src/main/java/org/openedx/course/presentation/handouts/HandoutsUIState.kt
course/src/main/java/org/openedx/course/presentation/handouts/HandoutsViewModel.kt
course/src/main/java/org/openedx/course/presentation/handouts/HandoutsWebViewFragment.kt
course/src/main/java/org/openedx/course/presentation/outline/CourseOutlineScreen.kt
course/src/main/java/org/openedx/course/presentation/ui/CourseVideosUI.kt
course/src/main/java/org/openedx/course/presentation/videos/CourseVideoViewModel.kt
course/src/main/java/org/openedx/course/presentation/videos/CourseVideosUIState.kt
course/src/main/res/values/strings.xml
course/src/test/java/org/openedx/course/presentation/dates/CourseDatesViewModelTest.kt
course/src/test/java/org/openedx/course/presentation/handouts/HandoutsViewModelTest.kt
course/src/test/java/org/openedx/course/presentation/videos/CourseVideoViewModelTest.kt
discussion/src/main/java/org/openedx/discussion/presentation/topics/DiscussionTopicsScreen.kt
discussion/src/main/java/org/openedx/discussion/presentation/topics/DiscussionTopicsUIState.kt
discussion/src/main/java/org/openedx/discussion/presentation/topics/DiscussionTopicsViewModel.kt
discussion/src/test/java/org/openedx/discussion/presentation/topics/DiscussionTopicsViewModelTest.kt

- Empty state for Home, Videos, Dates, and Discussion tabs.
- Empty state for handouts, and Announcements screen.
- [LEARNER-10039](https://2u-internal.atlassian.net/browse/LEARNER-10039)
- [Issue# 339](https://github.com/openedx/openedx-app-android/issues/339)
| Home Tab | Video Tab | Dates Tab |
| ------------- | ------------- | ------------- |
| <img src="https://github.com/user-attachments/assets/6e4c9dce-1950-4bf6-893d-5c62dbfe2eae"/> | <img src="https://github.com/user-attachments/assets/33603a32-bb6c-42c0-84f1-be8d1cc500de"/> | <img src="https://github.com/user-attachments/assets/2b11aee3-acb8-4423-adc3-a3ce2dffa6b6" /> |
| Discussion Tab | Handouts Screen | Announcements Screen |
| ------------- | ------------- | ------------- |
| <img …

feat: Course Level Error Handling for Empty States

---

course/src/main/java/org/openedx/course/presentation/unit/html/HtmlUnitFragment.kt

Fixed a bug that started to occur after merging this [https://github.com/openedx/openedx-app-android/pull/392](PR)

fix: bug when unable to see downloaded html content

---

course/src/main/java/org/openedx/course/presentation/ui/CourseVideosUI.kt

[LEARNER-10248](https://2u-internal.atlassian.net/browse/LEARNER-10248)
Fix crash of `IllegalArgumentException - current must not be NaN` during bulk download.
- Add validation to ensure that the progress value is not NaN.
**Steps to reproduce (specific courses)**
**Variant-1**
- Open the course named `Quantum Mechanics for Scientists and Engineers 1`
- Click on the video tab and start that bulk download.
- Try to expand the sections from the video tab, that lead the app to the crash.
**Variant-2**
- Open the course named `Quantum Mechanics for Scientists and Engineers 1`
- Click on the video tab and start that bulk download.
- Rapidly click on the arrow icon to expand the `section` from the Home tab, and the action leads the app to the crash.

fix: crash current must not be NaN during bulk download

---

course/src/main/java/org/openedx/course/presentation/container/CourseContainerViewModel.kt
course/src/test/java/org/openedx/course/presentation/container/CourseContainerViewModelTest.kt

•	Fixed display of the course structure in offline mode.
•	Performed minor code refactoring.

Fix: Course structure in offline mode
